#!/bin/bash
export MONGO_PORT=27017
export MONGO_HOST=classmongo@engr.oregonstate.edu
export MONGO_USER=cs290_woodjack
export MONGO_PASSWORD=cs290_woodjack
export MONGO_DB=cs290_woodjack
echo "Mongo server port opened on "$MONGO_PORT
npm start
