#!/bin/bash
export MONGO_PORT=27536
export MONGO_HOST=ds127536.mlab.com
export MONGO_USER=admin
export MONGO_PASSWORD=1234567
export MONGO_DB=cs290_final_project
echo "Mongo server port opened on "$MONGO_PORT
npm start
